import React, { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { BASE_URL } from "../../utils/const";

const ResumeReportsManagement = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [selectedReport, setSelectedReport] = useState(null);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await axios.get(`${BASE_URL}/admin/resume-reports`, {
          withCredentials: true,
        });
        setReports(res.data || []);
      } catch (err) {
        console.error(err);
        setError("Failed to load AI resume reports.");
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, []);

  const filteredReports = useMemo(() => {
    const query = search.trim().toLowerCase();
    if (!query) return reports;

    return reports.filter((report) => {
      const userName = `${report.user?.firstname || ""} ${report.user?.lastname || ""}`.toLowerCase();
      const values = [
        userName,
        report.user?.email,
        report.title,
        report.recommendedJobId?.title,
        report.recommendedJobId?.company,
        report.recommendedJobId?.role,
      ];

      return values.some((value) => value?.toLowerCase().includes(query));
    });
  }, [reports, search]);

  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-[60vh]">
        <span className="loading loading-spinner loading-lg text-primary"></span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white">AI Resume Reports</h1>
          <p className="text-sm text-white/50 mt-1">Review AI resume analysis results generated by users.</p>
        </div>
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search user, email, role, company..."
          className="input input-bordered bg-white/10 border-white/10 text-white w-full md:w-80"
        />
      </div>

      {error && (
        <div className="alert alert-error">
          <span>{error}</span>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="card bg-white/5 border border-white/10">
          <div className="card-body p-5">
            <p className="text-white/50 text-sm">Total Reports</p>
            <h2 className="text-3xl font-bold text-primary">{reports.length}</h2>
          </div>
        </div>
        <div className="card bg-white/5 border border-white/10">
          <div className="card-body p-5">
            <p className="text-white/50 text-sm">Average Score</p>
            <h2 className="text-3xl font-bold text-secondary">
              {reports.length
                ? Math.round(reports.reduce((sum, report) => sum + (report.matchScore || 0), 0) / reports.length)
                : 0}
              %
            </h2>
          </div>
        </div>
        <div className="card bg-white/5 border border-white/10">
          <div className="card-body p-5">
            <p className="text-white/50 text-sm">With Uploaded PDF</p>
            <h2 className="text-3xl font-bold text-accent">
              {reports.filter((report) => report.resumeUrl).length}
            </h2>
          </div>
        </div>
      </div>

      <div className="overflow-x-auto rounded-xl border border-white/10 bg-white/5 backdrop-blur-md">
        <table className="table">
          <thead className="text-white/60 bg-white/5">
            <tr>
              <th>User</th>
              <th>Target Role</th>
              <th>Recommended Job</th>
              <th>Score</th>
              <th>Generated</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.map((report) => (
              <tr key={report._id} className="border-white/10 hover:bg-white/5">
                <td>
                  <div className="flex items-center gap-3">
                    <div className="avatar">
                      <div className="w-10 rounded-full">
                        <img
                          src={report.user?.photoURL || "https://api.dicebear.com/7.x/avataaars/svg?seed=User"}
                          alt="User avatar"
                        />
                      </div>
                    </div>
                    <div>
                      <div className="font-semibold text-white">
                        {report.user?.firstname} {report.user?.lastname}
                      </div>
                      <div className="text-xs text-white/50">{report.user?.email}</div>
                    </div>
                  </div>
                </td>
                <td className="text-white">{report.title}</td>
                <td>
                  <div className="text-white">{report.recommendedJobId?.title || "Custom job description"}</div>
                  <div className="text-xs text-white/50">
                    {report.recommendedJobId?.company || report.recommendedJobId?.role || "User-provided target"}
                  </div>
                </td>
                <td>
                  <span className="badge badge-primary badge-lg">{report.matchScore || 0}%</span>
                </td>
                <td className="text-white/70">{new Date(report.createdAt).toLocaleDateString()}</td>
                <td>
                  <button
                    onClick={() => setSelectedReport(report)}
                    className="btn btn-sm btn-outline btn-primary"
                  >
                    View Result
                  </button>
                </td>
              </tr>
            ))}
            {filteredReports.length === 0 && (
              <tr>
                <td colSpan="6" className="text-center py-10 text-white/50">
                  No AI resume reports found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {selectedReport && (
        <div className="modal modal-open">
          <div className="modal-box max-w-5xl bg-[#0b0718] border border-white/10 text-white">
            <div className="flex items-start justify-between gap-4">
              <div>
                <h3 className="font-bold text-2xl">{selectedReport.title}</h3>
                <p className="text-white/50 text-sm mt-1">
                  {selectedReport.user?.firstname} {selectedReport.user?.lastname} - {selectedReport.user?.email}
                </p>
              </div>
              <button onClick={() => setSelectedReport(null)} className="btn btn-sm btn-circle btn-ghost">
                x
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-5">
              <div className="rounded-lg bg-white/5 border border-white/10 p-4">
                <p className="text-white/50 text-sm">Match Score</p>
                <p className="text-3xl font-bold text-primary">{selectedReport.matchScore || 0}%</p>
              </div>
              <div className="rounded-lg bg-white/5 border border-white/10 p-4">
                <p className="text-white/50 text-sm">Recommended Job</p>
                <p className="font-semibold">{selectedReport.recommendedJobId?.title || "Custom target"}</p>
              </div>
              <div className="rounded-lg bg-white/5 border border-white/10 p-4">
                <p className="text-white/50 text-sm">Original PDF</p>
                {selectedReport.resumeUrl ? (
                  <a href={selectedReport.resumeUrl} target="_blank" rel="noreferrer" className="link link-primary">
                    Open uploaded resume
                  </a>
                ) : (
                  <p className="text-white/40">Not available</p>
                )}
              </div>
            </div>

            <div className="space-y-5 max-h-[60vh] overflow-y-auto pr-2">
              <section>
                <h4 className="font-bold text-lg mb-2">Job Description Used</h4>
                <p className="text-sm text-white/70 bg-white/5 border border-white/10 rounded-lg p-4">
                  {selectedReport.jobDescription || "Not provided"}
                </p>
              </section>

              <section>
                <h4 className="font-bold text-lg mb-2">Skill Gaps</h4>
                <div className="flex flex-wrap gap-2">
                  {selectedReport.skillGaps?.length ? selectedReport.skillGaps.map((gap, index) => (
                    <span key={index} className="badge badge-outline badge-warning">
                      {gap.skill} - {gap.severity}
                    </span>
                  )) : <span className="text-white/40">No skill gaps listed.</span>}
                </div>
              </section>

              <section className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div>
                  <h4 className="font-bold text-lg mb-2">Technical Questions</h4>
                  <div className="space-y-3">
                    {selectedReport.technicalQuestions?.map((question, index) => (
                      <div key={index} className="bg-white/5 border border-white/10 rounded-lg p-4">
                        <p className="font-semibold">{question.question}</p>
                        <p className="text-xs text-white/50 mt-2">{question.intention}</p>
                      </div>
                    ))}
                  </div>
                </div>
                <div>
                  <h4 className="font-bold text-lg mb-2">Behavioral Questions</h4>
                  <div className="space-y-3">
                    {selectedReport.behavioralQuestions?.map((question, index) => (
                      <div key={index} className="bg-white/5 border border-white/10 rounded-lg p-4">
                        <p className="font-semibold">{question.question}</p>
                        <p className="text-xs text-white/50 mt-2">{question.intention}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </section>

              <section>
                <h4 className="font-bold text-lg mb-2">Preparation Plan</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {selectedReport.preparationPlan?.map((plan) => (
                    <div key={plan.day} className="bg-white/5 border border-white/10 rounded-lg p-4">
                      <p className="font-semibold">Day {plan.day}: {plan.focus}</p>
                      <ul className="list-disc list-inside text-sm text-white/60 mt-2">
                        {plan.tasks?.map((task, index) => <li key={index}>{task}</li>)}
                      </ul>
                    </div>
                  ))}
                </div>
              </section>
            </div>
          </div>
          <div className="modal-backdrop" onClick={() => setSelectedReport(null)}></div>
        </div>
      )}
    </div>
  );
};

export default ResumeReportsManagement;
